### ISSUE TITLE
Acquaint.XForm won't build. Fresh install of Xamarin via website.

### ISSUE THREAD

**Issue by MarkOBrienAU** [xamarinhq/app-acquaint#38]
First I tried running the sample project using the version of Xamarin installed by Visual studio, when that failed I then tried installing xamarin from the website which installed the JDK, a bunch of other dependencies. I'm using Visual Studio 2015 Update 3.

However I'm still getting the same compilation errors. I've included the full build log at the bottom, but here's a few important ones I think:

Error	CS0103	The name **'InitializeComponent**' does not exist in the current context	Acquaint.XForms	C:\Users\Mark\Source\Repos\app-acquaint\App\**Acquaint.XForms\Acquaint.XForms\App.xaml.cs**	13	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name '**AcquaintanceMap**' does not exist in the current context	Acquaint.XForms	C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\**Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs**	73	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name '**addAcquaintanceToolbarItem**' does not exist in the current context	Acquaint.XForms	C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\**Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs**	19	Active

To me it looks like its missing a dependency or  is building out of order. Is this something wrong on my end, or is the current build broken ?

```
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
Failed to resolve all project references for 'Acquaint.XForms'. The package restore result for 'C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms.UWP\Acquaint.XForms.UWP.csproj' may be incomplete.
Failed to resolve all project references for 'Acquaint.Models'. The package restore result for 'C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms.UWP\Acquaint.XForms.UWP.csproj' may be incomplete.
Failed to resolve all project references for 'Acquaint.Util'. The package restore result for 'C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms.UWP\Acquaint.XForms.UWP.csproj' may be incomplete.
Failed to resolve all project references for 'Acquaint.Data'. The package restore result for 'C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms.UWP\Acquaint.XForms.UWP.csproj' may be incomplete.
1>------ Rebuild All started: Project: Acquaint.ModelContracts, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: Acquaint.Util, Configuration: Debug Any CPU ------
1>  Acquaint.ModelContracts -> C:\Users\Mark\Source\Repos\app-acquaint\Common\Acquaint.ModelContracts\bin\Debug\Acquaint.ModelContracts.dll
2>  Acquaint.Util -> C:\Users\Mark\Source\Repos\app-acquaint\App\Common\Acquaint.Util\bin\Debug\Acquaint.Util.dll
3>------ Rebuild All started: Project: Acquaint.Abstractions, Configuration: Debug Any CPU ------
3>  Acquaint.Abstractions -> C:\Users\Mark\Source\Repos\app-acquaint\App\Common\Acquaint.Abstractions\bin\Debug\Acquaint.Abstractions.dll
4>------ Rebuild All started: Project: Acquaint.Models, Configuration: Debug Any CPU ------
5>------ Rebuild All started: Project: Acquaint.Common.Droid, Configuration: Debug Any CPU ------
6>------ Skipped Rebuild All: Project: Acquaint.Common.iOS, Configuration: Debug Any CPU ------
6>Project not selected to build for this solution configuration 
4>  Acquaint.Models -> C:\Users\Mark\Source\Repos\app-acquaint\App\Common\Acquaint.Models\bin\Debug\Acquaint.Models.dll
7>------ Rebuild All started: Project: Acquaint.Data, Configuration: Debug Any CPU ------
5>    Processing: obj\Debug\res\values\strings.xml
5>  Acquaint.Common.Droid -> C:\Users\Mark\Source\Repos\app-acquaint\App\Common\Acquaint.Common.Droid\bin\Debug\Acquaint.Common.Droid.dll
7>C:\Users\Mark\Source\Repos\app-acquaint\App\Common\Acquaint.Data\FilesystemOnlyAcquaintanceDataSource.cs(39,56,39,71): warning CS0067: The event 'FilesystemOnlyAcquaintanceDataSource.OnDataSyncError' is never used
7>  Acquaint.Data -> C:\Users\Mark\Source\Repos\app-acquaint\App\Common\Acquaint.Data\bin\Debug\Acquaint.Data.dll
8>------ Rebuild All started: Project: Acquaint.XForms, Configuration: Debug Any CPU ------
8>C:\Users\Mark\Source\Repos\app-acquaint\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing Acquaint.Data.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
8>C:\Users\Mark\Source\Repos\app-acquaint\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): warning : All projects referencing Acquaint.Models.csproj must install nuget package Microsoft.Bcl.Build. For more information, see http://go.microsoft.com/fwlink/?LinkID=317569.
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SetupPage.cs(15,13,15,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(14,13,14,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceEditPage.cs(12,13,12,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(17,69,17,158): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(24,71,24,160): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(31,72,31,162): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(38,71,38,160): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(45,64,45,185): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Views\FloatingActionButtonView.cs(52,69,52,148): warning CS0618: 'BindableProperty.Create<TDeclarer, TPropertyType>(Expression<Func<TDeclarer, TPropertyType>>, TPropertyType, BindingMode, BindableProperty.ValidateValueDelegate<TPropertyType>, BindableProperty.BindingPropertyChangedDelegate<TPropertyType>, BindableProperty.BindingPropertyChangingDelegate<TPropertyType>, BindableProperty.CoerceValueDelegate<TPropertyType>, BindableProperty.CreateDefaultValueDelegate<TDeclarer, TPropertyType>)' is obsolete: 'Generic versions of Create () are no longer supported and deprecated. They will be removed soon.'
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SplashPage.xaml.cs(16,13,16,32): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SetupPage.cs(24,43,24,67): error CS0103: The name 'DataPartitionPhraseEntry' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SetupPage.cs(26,17,26,41): error CS0103: The name 'DataPartitionPhraseEntry' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SetupPage.cs(28,17,28,41): error CS0103: The name 'DataPartitionPhraseEntry' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SetupPage.cs(33,44,33,68): error CS0103: The name 'DataPartitionPhraseEntry' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs(14,4,14,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs(19,28,19,54): error CS0103: The name 'addAcquaintanceToolbarItem' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs(21,5,21,8): error CS0103: The name 'fab' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceListPage.xaml.cs(26,31,26,49): error CS0103: The name 'refreshToolbarItem' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(35,17,35,32): error CS0103: The name 'AcquaintanceMap' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(71,21,71,36): error CS0103: The name 'AcquaintanceMap' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(73,21,73,36): error CS0103: The name 'AcquaintanceMap' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(76,13,76,28): error CS0103: The name 'AcquaintanceMap' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(78,17,78,32): error CS0103: The name 'AcquaintanceMap' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\AcquaintanceDetailPage.xaml.cs(44,34,44,36): warning CS0168: The variable 'ex' is declared but never used
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\App.xaml.cs(13,4,13,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SettingsPage.xaml.cs(14,4,14,23): error CS0103: The name 'InitializeComponent' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SettingsPage.xaml.cs(17,5,17,29): error CS0103: The name 'DataPartitionPhraseEntry' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SettingsPage.xaml.cs(18,5,18,29): error CS0103: The name 'DataPartitionPhraseEntry' does not exist in the current context
8>C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\Pages\SettingsPage.xaml.cs(22,5,22,27): error CS0103: The name 'BackendServiceUrlEntry' does not exist in the current context
9>------ Skipped Rebuild All: Project: Acquaint.XForms.iOS, Configuration: Debug iPhoneSimulator ------
9>Project not selected to build for this solution configuration 
10>------ Rebuild All started: Project: Acquaint.XForms.Droid, Configuration: Debug Any CPU ------
11>------ Rebuild All started: Project: Acquaint.XForms.UWP, Configuration: Debug x86 ------
12>------ Skipped Rebuild All: Project: Acquaint.XForms.UITest.iOS, Configuration: Debug Any CPU ------
12>Project not selected to build for this solution configuration 
11>  TargetPlatformIdentifier - UAP
11>C:\Users\Mark\Source\Repos\app-acquaint\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): error : Could not locate C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms.UWP\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.
11>C:\Users\Mark\Source\Repos\app-acquaint\App\packages\Microsoft.Bcl.Build.1.0.21\build\Microsoft.Bcl.Build.targets(243,5): error : Could not locate C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms.UWP\packages.config.  Ensure that this project has Microsoft.Bcl.Build installed and packages.config is located next to the project file.
11>CSC : error CS0006: Metadata file 'C:\Users\Mark\Source\Repos\app-acquaint\App\Acquaint.XForms\Acquaint.XForms\bin\Debug\Acquaint.XForms.dll' could not be found
10>  Consider app.config remapping of assembly "System.Runtime, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "4.0.0.0" [] to Version "4.1.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\Facades\System.Runtime.dll] to solve conflict and get rid of warning.
10>  Consider app.config remapping of assembly "System.Net.Primitives, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "3.9.0.0" [] to Version "4.0.0.0" [] to solve conflict and get rid of warning.
10>  Consider app.config remapping of assembly "System.Net.Http, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" from Version "1.5.0.0" [] to Version "4.0.0.0" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\MonoAndroid\v1.0\System.Net.Http.dll] to solve conflict and get rid of warning.
10>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3247: Found conflicts between different versions of the same dependent assembly. In Visual Studio, double-click this warning (or select it and press Enter) to fix the conflicts; otherwise, add the following binding redirects to the "runtime" node in the application configuration file: <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Runtime" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.1.0.0" newVersion="4.1.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Primitives" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding><assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"><dependentAssembly><assemblyIdentity name="System.Net.Http" culture="neutral" publicKeyToken="b03f5f7f11d50a3a" /><bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0" /></dependentAssembly></assemblyBinding>
10>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed.
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018: The "ResolveLibraryProjectImports" task failed unexpectedly.
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018: System.IO.FileNotFoundException: Could not load assembly 'Acquaint.XForms, Version=, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018: File name: 'Acquaint.XForms.dll'
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference reference, ReaderParameters parameters)
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName, ReaderParameters parameters)
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(String fullName)
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.GetAssembly(String fileName)
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Extract(ICollection`1 jars, ICollection`1 resolvedResourceDirectories, ICollection`1 resolvedAssetDirectories, ICollection`1 resolvedEnvironments)
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Xamarin.Android.Tasks.ResolveLibraryProjectImports.Execute()
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
10>C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(1060,2): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
13>------ Rebuild All started: Project: Acquaint.XForms.UITest.Android, Configuration: Debug Any CPU ------
========== Rebuild All: 6 succeeded, 4 failed, 3 skipped ==========
```

**Comment by jsauve** [comment]
I've commonly seen these messages when a Xamarin.Android install has failed on a Windows machine. 

First, ensure that Xamarin's Android support libraries have successfully installed. When you open a Xamarin.Android project for the first time since your Xamarin install, the build commonly takes a very long time. This often causes people to manually cancel their build because they think something is wrong. The thing that is taking a long time is the downloading, unzipping, and installing the Xamarin Android support libraries. If you cancel this before it finishes, the zips to will become corrupted, and all your subsequent builds will fail. You need to locate the folder path of the zips and the support libs, and delete them. This will prompt the build operation to re-try the download. Again, the build may take a long time, but it needs to be allowed to finish. 

The other thing that you may need to check is the ANDROID_SDK_HOME system variable. I think it's typically somewhere like `C:\Program Files (x86)\Android`. I'm not in front of my computer, so I dot have the exact path. 

These are just some common quirks that seems to be currently plaguing the Xamarin install experience when performed via the Visual Studio O 2015 installer. I typically have better success with the universal installer, instead of using Visual Studio. Hopefully these things get better in VS2017.
